spring:
  profiles:
    active: prod

  # 热部署
  devtools:
    restart:
      #设置开启热部署
      enabled: true

    livereload:
      #是否支持livereload
      enabled: false # we use gulp + BrowserSync for livereload

  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
    #加载的资源包文件缓存持续时间。 如果没有设置，捆绑包将被永久缓存。 如果没有指定持续时间后缀，将使用秒
    cache-duration: 3600

  #mysql连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.28.133:3306/pangolin_business?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: cuidaren
    password: CuiDaRen!23456

  #redis配置
  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    expireTime: 3600
    password: 123456

  #nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.135:8848

# PageHelper 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  #实体类所在的包
  type-aliases-package: com.base.saas.entity
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml

# 是否允許重複登錄 1 表示允許  0 表示不允許
duplicateLogin: 0
# 相当于两次请求间隔时间为600秒
sessionTimeout: 600

#允许用户密码错误次数
loginErrorLimit: 9

# 语言切换
localelist: zh_CN,en

# threadPooolConfig类上的配置参数
threadPool:
  corePoolSize: 200
  maxPoolSize: 500
  keepAliveSeconds: 60
  keepAliveTime: 20
  queueCapacity: 500
  allowCoreThreadTimeout: false
  threadNamePrefix: base-
