spring:
  profiles:
    active: dev
    include: swagger


  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saas-base?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    name: writesource
    username: root
    password: root
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      idle-timeout: 60000
      connection-timeout: 60000
      validation-timeout: 4000
      ogin-timeout: 5
      max-lifetime: 6000
      maximum-pool-size: 5

  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    expireTime: 3600
    password: GAO2651qiang

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


threadPool:
  corePoolSize: 200
  maxPoolSize: 500
  keepAliveSeconds: 60
  keepAliveTime: 20
  queueCapacity: 500
  allowCoreThreadTimeout: false
  threadNamePrefix: saas-

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
