server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: saas-zuul-gateway
  profiles:
    active: dev
  data:
    mongodb:
      uri: mongodb://192.168.102.188:27017
      database: customer_file_db
  redis:
    database: 5
    host: 192.168.102.109
    port: 6379 #端口
    password: 123456
    timeout: 30000 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        time-between-eviction-runs: -1 #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
sessionTimeout: 600
data:
  isChangeDataSource: 0
