server:
  port: 9000

spring:
  application:
    name: saas-zuul-gateway
  profiles:
#    active: @spring.profiles.active@
    active: dev
  data:
    mongodb:
      uri: mongodb://192.168.102.188:27017
      database: customer_file_db

  redis:
    database: 5
    host: 192.168.102.109
    port: 6379
    expireTime: 3600
    password: 123456

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
sessionTimeout: 600
data:
  isChangeDataSource: 0
