spring:
  profiles:
    active: prod

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.102.135:8848

  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    expireTime: 3600
    password: xxx
