spring:
    application:
        name: ran-fenqi-manager
    profiles:
#        active: @spring.profiles.active@
      active: dev
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false
    messages:
      basename: i18n/messages
      cache-duration: 3600
server:
  session:

  servlet:
    session:
      cookie:
        http-only: true
      timeout: 36000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
quartz:
  enabled: true
mybatis:
  type-aliases-package: cn.fintecher.entity
  mapper-locations: classpath:mapper/*.xml

# 是否允許重複登錄 1 表示允許  0 表示不允許
duplicateLogin: 1
sessionTimeout: 600
#允许用户密码错误次数
loginErrorLimit: 99


localelist: zh_CN,en

fdfs:
  thumb-image:
    height: 60
    width: 60
  tracker-list:
    - 192.168.102.188:22122 #fastdfs的tracker服务地址,是一个列表可以配置多个
  so-timeout: 1501 #读取时间
  connect-timeout: 1601 #连接超时时间

data:
  isChangeDataSource: 0
