spring:
    application:
        name: ran-fenqi-system-web
    profiles:
#        active: @spring.profiles.active@
      active: dev
    jackson:
        serialization.write_dates_as_timestamps: true
    mvc:
        favicon:
            enabled: false
    messages:
      basename: i18n/messages
      cache-duration: 3600
    http:

    servlet:
      multipart:
        enabled: false
server:
    session:

    servlet:
      session:
        cookie:
          http-only: true
        timeout: 36000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
quartz:
  enabled: true
mybatis:
  type-aliases-package: cn.fintecher.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: true

sessionTimeout: 600
#允许用户密码错误次数
loginErrorLimit: 99

fdfs:
  thumb-image:
    height: 60
    width: 60
  tracker-list:
    - 192.168.102.188:22122 #fastdfs的tracker服务地址,是一个列表可以配置多个
  so-timeout: 1501 #读取时间
  connect-timeout: 1601 #连接超时时间
data:
  isChangeDataSource: 0
