spring:
  profiles:
    active: dev
    include: swagger


  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    database: 5
    host: 127.0.0.1
    port: 6379
    expireTime: 3600
    password: GAO2651qiang
