spring:
    profiles:
        active: test
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false # we use gulp + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
        serialization.write_dates_as_timestamps: true
    datasource:
        platform: mysql
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.102.116:3306/zr_fenqi?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: zwjkhf
        password: zwjkhf123
        max-active: 5
        maximum-pool-size: 5
    rabbitmq:
        username: 2.2.3
        password: 2.2.3
        host: 192.168.3.2
        virtual-host: 2.2.3
        port: 5672
    cache:
        jcache:
            config: ehcache.xml
    redis:
        database: 4
        host: 192.168.3.2
        port: 6379
        expireTime: 3600
        password: redis123456
eureka:
  instance:
    hostname: business-service
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://localhost:8761/eureka/
server:
    port: 9001

cuibei:
  baiduMap:
    webUrl: http://api.map.baidu.com/cloudgc/v1?city=全国&ak=
    webAk: lHaYCXlRADlhW0fnv8tpIhCfqD85pTSr

threadPool:
  corePoolSize: 10
  maxPoolSize: 200
  keepAliveSeconds : 60
  queueCapacity: 500
  allowCoreThreadTimeout : false
  threadNamePrefix: pangolin-

RSAPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCC09lmmyQ/xwGZ3ALAlxBhhAVX81EfAwIFnonavcJF6y5c4T8FC/YZSD4URcC7fyTmCZnwEiIAQhr33Qgineep5bY85LL4gWFlGis5FICbR0yj1Knl5JrZmCqtkK5uVItGwfb9iXYucAirhDtGdxBMurSid8o2y2wru6dXzQWrSQIDAQAB